version: "3.6"

services:
  web:
    image: nginx
    ports:
      - "80:80"
    container_name: english-nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/:ro
    depends_on:
      - php
    networks:
      - test-block

  php:
    build:
      context: ./docker/php
    image: english-php:1.1
    container_name: english-php
    volumes:
      - .:/var/www/
    depends_on:
      - mysql
    networks:
      - test-block

  mysql:
    image: mysql
    container_name: english-mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: sd@h4Dq2K
      MYSQL_DATABASE: mburnaevg4_fulls
      MYSQL_USER: app_user
      MYSQL_PASSWORD: ak#rDb5dLg
    volumes:
      - "./docker/mysql/script:/docker-entrypoint-initdb.d"
    networks:
      - test-block

networks:
  test-block:
    driver: bridge